{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-28T20:17:59Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      release 0.0.296
    sha: 26cb49bef832745ee23494b7a4a587131da891da
  gitHttpUrl: https://github.com/ankitm123/jx-cli
  gitOwner: ankitm123
  gitRepository: jx-cli
  name: '{{ .Chart.Name }}'
  version: 3.1.145
status: {}
 
{{- end }}
